embedding_model = "BAAI/bge-small-en-v1.5"
query_model = "HuggingFaceTB/SmolLM2-1.7B-Instruct"
k = 10
[data_source]
# url = "https://raw.githubusercontent.com/run-llama/llama_index/main/docs/docs/examples/data/paul_graham/paul_graham_essay.txt"
url = "https://en.wikipedia.org/wiki/Amitabh_Bachchan"