embedding_model = "BAAI/bge-small-en-v1.5"
query_model = "HuggingFaceTB/SmolLM2-135M-Instruct"

[data_source]
url = "https://raw.githubusercontent.com/run-llama/llama_index/main/docs/docs/examples/data/paul_graham/paul_graham_essay.txt"